### ISSUE TITLE
**Name of the team:**  TheAnimators

### ISSUE THREAD

**Issue by dpsd18023** [merkourisa/Digital-Storytelling-Group-Assignment#2]
**Name of the team:**  TheAnimators
**GitHub url:** [dpsd18023](https://github.com/dpsd18023/Digital-Storytelling-Group-Assignment)
**Accepting new member:** Yes

| # | AM | GitHub profile |
|       :---:         |     :---:      |     :---:      |
| 1  | Dpsd18023    |  https://github.com/dpsd18023  |
| 2  | Dpsd18108    |  https://github.com/dpsd18108  |
| 3  |       |     |
| 4  |       |     |
| 5  |       |     |
| 6  |       |     |

**Comment by ElenaLyra** [comment]
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">Διεύθυνση url GitHub:<span> </span></font></font></strong><a href="https://github.com/dpsd18023/Digital-Storytelling-Group-Assignment" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">dpsd19068</font></font></a><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">Αποδοχή νέου μέλους:</font></font></strong><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;"><span> </span>Ναι</font></font></p><table role="table" style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; margin-top: 0px; margin-bottom: 0px !important; display: block; width: max-content; max-width: 100%; overflow: auto;"><thead style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><th align="center" style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">#</font></font></th><th align="center" style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">ΕΙΜΑΙ</font></font></th><th align="center" style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">Προφίλ GitHub</font></font></th></tr></thead><tbody style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; margin-bottom: 0px; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">1</font></font></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; margin-bottom: 0px; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">Dpsd18023</font></font></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><a href="https://github.com/dpsd18023" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; margin-bottom: 0px;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">https://github.com/dpsd18023</font></font></a></td></tr><tr style="box-sizing: border-box; background-color: var(--color-canvas-subtle); border-top: 1px solid var(--color-border-muted);"><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; margin-bottom: 0px; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">2</font></font></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; margin-bottom: 0px; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">Dpsd18108</font></font></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><a href="https://github.com/dpsd18108" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; margin-bottom: 0px;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">https://github.com/dpsd18108</font></font></a></td></tr><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; margin-bottom: 0px; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">3</font></font></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"></td></tr><tr style="box-sizing: border-box; background-color: var(--color-canvas-subtle); border-top: 1px solid var(--color-border-muted);"><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; margin-bottom: 0px; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">4</font></font></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"></td></tr><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"><font style="box-sizing: border-box; margin-bottom: 0px; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">5</font></font></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);"></td></tr><tr style="box-sizing: border-box; background-color: var(--color-canvas-subtle); border-top: 1px solid var(--color-border-muted);"><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><font style="box-sizing: border-box; margin-bottom: 0px; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">6</font></font></td><td align="center" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><br class="Apple-interchange-newline">Διεύθυνση url GitHub: [dpsd18023](https://github.com/dpsd18023/Digital-Storytelling-Group-Assignment)
Αποδοχή νέου μέλους: Όχι

#	ΕΙΜΑΙ	Προφίλ GitHub
1	Dpsd19068	https://github.com/ElenaLyra
2	Dpsd19067	https://github.com/dimitrisl11
3	Dpsd19014    https://github.com/ZoiGalanidpsd19014	
4	Dpsd19071    https://github.com/GeorgeDPSD	
5	Dpsd19103    https://github.com/Stathenia
6

**Comment by dpsd18023** [comment]
Καλησπέρα κ. Μερκούρη, δεν μπορούμε να βρούμε τι κάναμε λάθος με το σχόλιο για τη δημιουργία ομάδας.
Έχουμε δημιουργήσει ένα [σχόλιο](https://github.com/merkourisa/Digital-Storytelling-Group-Assignment/discussions/1#discussioncomment-5295341) στο [Creating Teams #1 ](https://github.com/merkourisa/Digital-Storytelling-Group-Assignment/discussions/1) και στο "GitHub url:" βάλαμε τον παρακάτω σύνδεσμο https://github.com/dpsd18023/Digital-Storytelling-Group-Assignment. 
Πέρα από αυτά, δημιουργήσαμε και αυτό το [discussion](https://github.com/dpsd18023/Digital-Storytelling-Group-Assignment/discussions/1 ), αλλά δεν το έχουμε χρησιμοποιήσει κάπου.

**Comment by merkourisa** [comment]
@dpsd18023 καλησπέρα, το σχόλιο για τη δημιουργία της ομάδας θα πρέπει να γίνει στο αντίστοιχο [discussion](https://github.com/merkourisa/Digital-Storytelling-Group-Assignment/discussions/1) και όχι στο νέο issue που ανοίξατε. Για έκανα αυτό το σχόλιο και έκλεισα το νέο issue
